name: Deploy Docker Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      
      - name: Checkout code
        uses: actions/checkout@v3

      
      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      
      - name: Install EB CLI
        run: pip install --upgrade awsebcli

      
      - name: Initialize EB
        run: |
          cd backend
          eb init todo-backend --platform "Docker" --region us-east-1 --verbose
          eb use todo-env

      
      - name: Deploy to Elastic Beanstalk
        run: |
          cd backend
          eb deploy todo-env --staged

      
      - name: Wait for EB health
        run: |
          URL="http://todo-env.eba-chkm7fym.us-east-1.elasticbeanstalk.com/tasks"
          MAX_RETRIES=12
          SLEEP_SECONDS=10
          for i in $(seq 1 $MAX_RETRIES); do
            STATUS=$(curl -s -o /dev/null -w "%{http_code}" $URL)
            echo "Attempt $i: HTTP status $STATUS"
            if [ "$STATUS" -eq 200 ]; then
              echo "Backend is healthy!"
              exit 0
            fi
            sleep $SLEEP_SECONDS
          done
          echo "Backend did not become healthy in time."
          exit 1
