name: Deploy Docker Backend to Elastic Beanstalk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Install EB CLI
        run: pip install --upgrade awsebcli

      - name: Initialize EB
        run: |
          eb init todo-backend --platform "Docker" --region us-east-1 --verbose
          eb use todo-env

      - name: Deploy to Elastic Beanstalk
        run: eb deploy todo-env --staged

      - name: Test backend
        run: |
          sleep 10
          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" http://todo-env.eba-chkm7fym.us-east-1.elasticbeanstalk.com/tasks)
          echo "HTTP status: $STATUS_CODE"
          if [ "$STATUS_CODE" -ne 200 ]; then
            echo "Backend test failed"
            exit 1
          fi
